### ISSUE TITLE
Can't compile on MacOS 10.11.3

### ISSUE THREAD

**Issue by MichaelHoelzl** [redox-os/redox#787]
#Hi,
i get this problem.

```
undefined reference to `log10'
undefined reference to `pow'
```

```
Compiling coreutils v0.1.0 (file:///Users/michaelhoelzl/redox/programs/coreutils)
warning: ignoring --out-dir flag due to -o flag.

error: linking with `x86_64-elf-gcc` failed: exit code: 1
  |
  = note: "x86_64-elf-gcc" "-m64" "-nostdlib" "-static" "-L" "/Users/michaelhoelzl/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-redox/lib" "filesystem/bin/dd.0.o" "-o" "filesystem/bin/dd" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "build/userspace" "-L" "/Users/michaelhoelzl/redox/programs/coreutils/target/x86_64-unknown-redox/release/deps" "-L" "/Users/michaelhoelzl/redox/programs/coreutils/target/release/deps" "-L" "/Users/michaelhoelzl/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-redox/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/Users/michaelhoelzl/redox/programs/coreutils/target/x86_64-unknown-redox/release/deps/libcoreutils-0842b6525fe136b1.rlib" "/Users/michaelhoelzl/redox/build/userspace/libstd.rlib" "/Users/michaelhoelzl/redox/build/userspace/libunwind-8778138f894afac9.rlib" "/Users/michaelhoelzl/redox/build/userspace/liblibc-78791a3fcfd92d68.rlib" "/Users/michaelhoelzl/redox/build/userspace/libsyscall-3325590d167978be.rlib" "/Users/michaelhoelzl/redox/build/userspace/librand.rlib" "/Users/michaelhoelzl/redox/build/userspace/libcollections.rlib" "/Users/michaelhoelzl/redox/build/userspace/libstd_unicode.rlib" "/Users/michaelhoelzl/redox/build/userspace/liballoc.rlib" "/Users/michaelhoelzl/redox/build/userspace/libspin-320fb8ccccfe7367.rlib" "/Users/michaelhoelzl/redox/build/userspace/libcompiler_builtins-fd8424cbf7eab50a.rlib" "/Users/michaelhoelzl/redox/build/userspace/libralloc-ef7cfc16e012a7a4.rlib" "/Users/michaelhoelzl/redox/build/userspace/libralloc_shim-8ace3497bf57d728.rlib" "/Users/michaelhoelzl/redox/build/userspace/libsyscall-9542e66cfe957b75.rlib" "/Users/michaelhoelzl/redox/build/userspace/libpanic_abort-bbe5d91d109b2fc9.rlib" "/Users/michaelhoelzl/redox/build/userspace/libcore.rlib" "build/userspace/libopenlibm.a"
  = note: /Users/michaelhoelzl/redox/programs/coreutils/target/x86_64-unknown-redox/release/deps/libcoreutils-0842b6525fe136b1.rlib(coreutils-0842b6525fe136b1.0.o): In function `coreutils::to_human_readable_string::h4c6a1b1361435144':
coreutils.cgu-0.rs:(.text._ZN9coreutils24to_human_readable_string17h4c6a1b1361435144E+0x7c): undefined reference to `log10'
coreutils.cgu-0.rs:(.text._ZN9coreutils24to_human_readable_string17h4c6a1b1361435144E+0x9c): undefined reference to `pow'
collect2: Fehler: ld gab 1 als Ende-Status zurück


error: aborting due to previous error

error: Could not compile `coreutils`.

To learn more, run the command again with --verbose.
make: *** [filesystem/bin/dd] Error 101
```

**Comment by MichaelHoelzl** [comment]
and now

```
error: linking with `x86_64-elf-gcc` failed: exit code: 1
  |
  = note: "x86_64-elf-gcc" "-m64" "-nostdlib" "-static" "-L" "/Users/michaelhoelzl/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-redox/lib" "filesystem/bin/dd.0.o" "-o" "filesystem/bin/dd" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "build/userspace" "-L" "/Users/michaelhoelzl/redox/programs/coreutils/target/x86_64-unknown-redox/release/deps" "-L" "/Users/michaelhoelzl/redox/programs/coreutils/target/release/deps" "-L" "/Users/michaelhoelzl/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-unknown-redox/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/Users/michaelhoelzl/redox/programs/coreutils/target/x86_64-unknown-redox/release/deps/libcoreutils-0842b6525fe136b1.rlib" "/Users/michaelhoelzl/redox/build/userspace/libstd.rlib" "/Users/michaelhoelzl/redox/build/userspace/libunwind-8778138f894afac9.rlib" "/Users/michaelhoelzl/redox/build/userspace/liblibc-78791a3fcfd92d68.rlib" "/Users/michaelhoelzl/redox/build/userspace/libsyscall-3325590d167978be.rlib" "/Users/michaelhoelzl/redox/build/userspace/librand.rlib" "/Users/michaelhoelzl/redox/build/userspace/libcollections.rlib" "/Users/michaelhoelzl/redox/build/userspace/libstd_unicode.rlib" "/Users/michaelhoelzl/redox/build/userspace/liballoc.rlib" "/Users/michaelhoelzl/redox/build/userspace/libspin-320fb8ccccfe7367.rlib" "/Users/michaelhoelzl/redox/build/userspace/libcompiler_builtins-fd8424cbf7eab50a.rlib" "/Users/michaelhoelzl/redox/build/userspace/libralloc-ef7cfc16e012a7a4.rlib" "/Users/michaelhoelzl/redox/build/userspace/libralloc_shim-8ace3497bf57d728.rlib" "/Users/michaelhoelzl/redox/build/userspace/libsyscall-9542e66cfe957b75.rlib" "/Users/michaelhoelzl/redox/build/userspace/libpanic_abort-bbe5d91d109b2fc9.rlib" "/Users/michaelhoelzl/redox/build/userspace/libcore.rlib" "build/userspace/libopenlibm.a"
  = note: /Users/michaelhoelzl/redox/programs/coreutils/target/x86_64-unknown-redox/release/deps/libcoreutils-0842b6525fe136b1.rlib(coreutils-0842b6525fe136b1.0.o): In function `coreutils::to_human_readable_string::h4c6a1b1361435144':
coreutils.cgu-0.rs:(.text._ZN9coreutils24to_human_readable_string17h4c6a1b1361435144E+0x7c): undefined reference to `log10'
coreutils.cgu-0.rs:(.text._ZN9coreutils24to_human_readable_string17h4c6a1b1361435144E+0x9c): undefined reference to `pow'
collect2: Fehler: ld gab 1 als Ende-Status zurück


error: aborting due to previous error

error: Could not compile `coreutils`.

To learn more, run the command again with --verbose.
```

**Comment by Mouvedia** [comment]
related: #786

**Comment by jackpot51** [comment]
This should be fixed now. If you have issues with the latest master, please post on #804
